[package]
name = "pallet-chainbridge-support"
version = "0.1.0"
edition = "2021"
authors = ["Octopus Network <hi@oct.network>", "UINB Tech<hi@fusotao.org>"]
license = "Apache-2.0"
repository = "https://github.com/uinb/fusotao-chainbridge.git"
description = "FRAME pallet used to Crosschain transfer."
readme = "README.md"
[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
borsh = { version = "0.9.0", default-features = false }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }

frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18", default-features = false }

[features]
default = ["std"]
std = [
	"borsh/std",
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-std/std",
]
